Add quickemu updates

diff --git a/quickemu b/quickemu
--- a/quickemu
+++ b/quickemu
@@ -145,6 +145,11 @@ function vm_boot() {
     echo " - BIOS:     Legacy"
   fi
 
+  if [ -z "${iso}" ]; then
+    echo " - ERROR! You haven't specified an ISO image to boot from."
+    exit 1
+  fi
+
   local hdd=""
   # Has the no hdd option been requested?
   if [ "${no_hdd}" -eq 1 ]; then
@@ -189,7 +194,7 @@ function vm_boot() {
   echo " - Disk:     ${disk_img} (${disk})"
 
   # Has the status quo option been requested?
-  if [ "${status_quo}" -eq 1 ] && [ -z "${iso}" ]; then
+  if [ "${status_quo}" -eq 1 ]; then
     STATUSQUO="-snapshot"
     echo " - Existing disk state will be preserved, no changes to the disk/snapshot will be committed."
   fi
@@ -401,7 +406,7 @@ if [ ! -e "${QEMU}" ] && [ ! -e "${QEMU_IMG}" ]; then
   exit 1
 fi
 
-if [ -n "${VM}" ] || [ -e "${VM}" ]; then
+if [ -n "${VM}" ] && [ -e "${VM}" ]; then
   source "${VM}"
   if [ -z "${disk_img}" ] && [ -f "${no_hdd}" ]; then
     echo " - ERROR! No disk_img defined."
